# Generated by Django 5.0.3 on 2024-04-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
